version: "3.9"
services:
  app:
    image: users_api
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - db.env
  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    volumes:
      - ../mysql_data:/var/lib/mysql
    expose:
      - 3306
    env_file:
      - db.env
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 5